package util;

/**
 * @author Fabian Widmann
 */
public enum UserOperations {
    CREATE_CATEGORY, CREATE_CARD, CREATE_DECK, CREATE_RATING, CREATE_GROUP,

    DELETE_ANSWER, DELETE_CARD, DELETE_DECK, DELETE_CATEGORY, DELETE_USER, DELETE_RATING, DELETE_GROUP,

    EDIT_DECK, EDIT_CARD_QUESTION, EDIT_ANSWER, EDIT_CATEGORY, EDIT_USER, EDIT_RATING, EDIT_GROUP


}
